import ExcelJS from "exceljs";
import type { ReportData, ReportParams } from "@/types/api";

const HEADER_FILL: ExcelJS.Fill = {
  type: "pattern",
  pattern: "solid",
  fgColor: { argb: "FF0F62FE" },
};

const HEADER_FONT: Partial<ExcelJS.Font> = {
  bold: true,
  color: { argb: "FFFFFFFF" },
};

/**
 * Applies consistent header row styling to a worksheet.
 */
function styleHeaderRow(row: ExcelJS.Row, colCount: number): void {
  for (let i = 1; i <= colCount; i++) {
    const cell = row.getCell(i);
    cell.fill = HEADER_FILL;
    cell.font = HEADER_FONT;
    cell.alignment = { vertical: "middle" };
  }
  row.height = 22;
}

/**
 * Generates an XLSX workbook from the provided report data.
 * Sheet 1: Summary metrics  ·  Sheet 2: Raw request rows  ·  Sheet 3: Cost breakdown
 *
 * @param params - Report parameters
 * @param data - Aggregated report data
 * @returns A Blob containing the generated .xlsx file
 */
export async function generateXlsx(
  params: ReportParams,
  data: ReportData
): Promise<Blob> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Pangreksa Console";
  wb.created = new Date();

  // ── Sheet 1: Summary ────────────────────────────────────────────────────────
  const summary = wb.addWorksheet("Summary");
  const summaryHeaders = ["Metric", "Value"];
  const headerRow = summary.addRow(summaryHeaders);
  styleHeaderRow(headerRow, summaryHeaders.length);

  Object.entries(data.summary).forEach(([key, value]) => {
    summary.addRow([key.replace(/_/g, " "), value]);
  });

  summary.getColumn(1).width = 30;
  summary.getColumn(2).width = 20;

  // ── Sheet 2: Requests ────────────────────────────────────────────────────────
  const requests = wb.addWorksheet("Requests");
  if (data.rows.length > 0) {
    const columns = Object.keys(data.rows[0] ?? {});
    const reqHeaderRow = requests.addRow(columns.map((c) => c.replace(/_/g, " ")));
    styleHeaderRow(reqHeaderRow, columns.length);

    data.rows.forEach((row) => {
      requests.addRow(columns.map((col) => row[col] ?? ""));
    });

    // Format cost columns as USD currency
    columns.forEach((col, idx) => {
      if (col.includes("cost") || col.includes("usd")) {
        requests.getColumn(idx + 1).numFmt = '"$"#,##0.0000';
      }
      if (col.includes("tokens")) {
        requests.getColumn(idx + 1).numFmt = "#,##0";
      }
      requests.getColumn(idx + 1).width = Math.max(col.length + 4, 12);
    });
  }

  // ── Sheet 3: Cost Breakdown ──────────────────────────────────────────────────
  const costs = wb.addWorksheet("Cost Breakdown");
  const costHeaders = ["Model", "Provider", "Requests", "Input Tokens", "Output Tokens", "Total Cost (USD)"];
  const costHeaderRow = costs.addRow(costHeaders);
  styleHeaderRow(costHeaderRow, costHeaders.length);

  // Group by model from data.rows if available
  const byModel = new Map<string, { requests: number; input: number; output: number; cost: number }>();
  data.rows.forEach((row) => {
    const model = String(row["model"] ?? "unknown");
    const existing = byModel.get(model) ?? { requests: 0, input: 0, output: 0, cost: 0 };
    existing.requests += Number(row["request_count"] ?? 1);
    existing.input += Number(row["input_tokens"] ?? 0);
    existing.output += Number(row["output_tokens"] ?? 0);
    existing.cost += Number(row["cost_usd"] ?? 0);
    byModel.set(model, existing);
  });

  byModel.forEach((vals, model) => {
    const row = costs.addRow([model, "—", vals.requests, vals.input, vals.output, vals.cost]);
    row.getCell(6).numFmt = '"$"#,##0.0000';
  });

  costs.columns.forEach((col) => { col.width = 18; });

  // ── Metadata sheet ───────────────────────────────────────────────────────────
  const meta = wb.addWorksheet("Report Info");
  meta.addRow(["Report type", params.type]);
  meta.addRow(["Period from", params.from]);
  meta.addRow(["Period to", params.to]);
  meta.addRow(["Scope", params.scope]);
  meta.addRow(["Generated at", data.meta.generated_at]);
  meta.addRow(["Generated by", data.meta.generated_by]);
  meta.getColumn(1).width = 20;
  meta.getColumn(2).width = 40;

  const buffer = await wb.xlsx.writeBuffer();
  return new Blob([buffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
}
