package repository

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/pangreksa/ai-gateway-engine/pkg/model"
)

// ConsoleSession is a refresh token session for the web console.
//
// Each successful login creates one session row. The refresh_token_hash
// field stores the SHA-256 hex digest of the raw refresh token; the raw
// token is only held in the browser cookie and never persisted.
type ConsoleSession struct {
	// ID is the UUID primary key of the session.
	ID string
	// UserID is the UUID of the authenticated user who owns this session.
	UserID string
	// RefreshTokenHash is the SHA-256 hex digest of the raw refresh token.
	RefreshTokenHash string
	// IPAddress is the remote address at session creation time (may be empty).
	IPAddress string
	// UserAgent is the browser/client user-agent string (may be empty).
	UserAgent string
	// ExpiresAt is the time after which the session is considered invalid.
	ExpiresAt time.Time
	// CreatedAt is the timestamp when the session was created.
	CreatedAt time.Time
}

// ConsoleSessionRepository handles console_sessions CRUD.
//
// Thread-safety: safe for concurrent use; all operations use the shared Pool.
type ConsoleSessionRepository struct {
	// Pool is the underlying pgx connection pool.
	Pool *pgxpool.Pool
}

// NewConsoleSessionRepository constructs a ConsoleSessionRepository backed by
// the given DB connection pool.
func NewConsoleSessionRepository(db *DB) *ConsoleSessionRepository {
	return &ConsoleSessionRepository{Pool: db.Pool}
}

// Create inserts a new session row into console_sessions.
//
// The session ID is generated by the database (gen_random_uuid()).
// After Create returns, s.ID is not populated; callers that need the
// generated ID should query by refresh_token_hash immediately after.
func (r *ConsoleSessionRepository) Create(ctx context.Context, session *ConsoleSession) error {
	const q = `
		INSERT INTO console_sessions
			(user_id, refresh_token_hash, ip_address, user_agent, expires_at)
		VALUES ($1, $2, $3::INET, $4, $5)
	`

	// Use NULL for empty IP address to satisfy the INET column type.
	var ipAddr *string
	if session.IPAddress != "" {
		ipAddr = &session.IPAddress
	}

	_, err := r.Pool.Exec(ctx, q,
		session.UserID,
		session.RefreshTokenHash,
		ipAddr,
		session.UserAgent,
		session.ExpiresAt,
	)
	if err != nil {
		return fmt.Errorf("ConsoleSessionRepository.Create: exec: %w", err)
	}
	return nil
}

// FindByTokenHash looks up a session by its refresh_token_hash.
//
// Only non-expired sessions are returned; expired sessions are treated as
// not found. Returns model.ErrNotFound when no valid session matches the hash.
func (r *ConsoleSessionRepository) FindByTokenHash(ctx context.Context, hash string) (*ConsoleSession, error) {
	const q = `
		SELECT id, user_id, refresh_token_hash,
		       COALESCE(ip_address::TEXT, ''), user_agent,
		       expires_at, created_at
		FROM console_sessions
		WHERE refresh_token_hash = $1
		  AND expires_at > NOW()
	`

	row := r.Pool.QueryRow(ctx, q, hash)

	var s ConsoleSession
	err := row.Scan(
		&s.ID,
		&s.UserID,
		&s.RefreshTokenHash,
		&s.IPAddress,
		&s.UserAgent,
		&s.ExpiresAt,
		&s.CreatedAt,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("ConsoleSessionRepository.FindByTokenHash: %w", model.ErrNotFound)
		}
		return nil, fmt.Errorf("ConsoleSessionRepository.FindByTokenHash: scan: %w", err)
	}

	return &s, nil
}

// Delete removes a session by its UUID (used for logout / token revocation).
//
// Deleting a non-existent session is not treated as an error.
func (r *ConsoleSessionRepository) Delete(ctx context.Context, id string) error {
	const q = `DELETE FROM console_sessions WHERE id = $1`

	_, err := r.Pool.Exec(ctx, q, id)
	if err != nil {
		return fmt.Errorf("ConsoleSessionRepository.Delete: exec: %w", err)
	}
	return nil
}

// DeleteExpired removes all sessions whose expires_at is in the past.
//
// Returns the number of rows deleted. This method is intended to be called
// from a periodic cleanup job to prevent unbounded table growth.
func (r *ConsoleSessionRepository) DeleteExpired(ctx context.Context) (int64, error) {
	const q = `DELETE FROM console_sessions WHERE expires_at <= NOW()`

	tag, err := r.Pool.Exec(ctx, q)
	if err != nil {
		return 0, fmt.Errorf("ConsoleSessionRepository.DeleteExpired: exec: %w", err)
	}
	return tag.RowsAffected(), nil
}
